server:
  port: 80
  servlet:
    context-path: /

spring:

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.106.238:3306/education?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
#  redis:
#    host: 10.125.50.16
#    password: NQSSks#Re
#    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hbu.test.entity
  mapper-locations: classpath:mapper/*Mapper.xml